# Site Settings
site_name: Luke Richardson aka Lukeoson
site_url: https://hello.lukeoson.com
repo_url: https://github.com/lukeoson/lukeoson-mkdocs
repo_name: lukeoson/lukeoson-mkdocs
copyright: Copyright &copy; 2023 Lloret





theme:
  name: material
