# Site Settings
site_name: !ENV [SITE_NAME, 'Luke Richardson']
site_url: !ENV [SITE_URL, "https://lukeoson.com/"]
repo_url: !ENV [REPO_URL, "https://github.com/lukeoson/lukeoson-mkdocs"]
repo_name: !ENV [REPO_NAME, "lukeoson.com"]
copyright: !ENV [COPYRIGHT, "Copyright 2023 Lukeoson"]

# Navigation 
nav:

# Homepage
  - Home:
    - Home: index.md
    - My Bookshelf: books.md
    - My Favourite Quotes: quotes.md
    - My Favourite Words: words.md

# Resume
  - Hire Me: 
    - Luke's Resume: Hire-Me/index.md

# Blog
  - Blog:
    - Blog: blog/index.md




# Infrastructure as Code
#  - Infrastructure as Code: 
#    - IaC/index.md
#    - GIT:
#      - IaC/Git/index.md
#    - MKDOCS:
#      - IaC/Mkdocs/index.md
  
# Foundational Concepts  
# - Network Rudiments: 
#   - Network-Rudiments/index.md
#   - Subnetting:
#     - Network-Rudiments/Subnetting/index.md
#     - Hello: Network-Rudiments/Subnetting/whoami.md
#     - Subnet Things: Network-Rudiments/Subnetting/subnetting.md
#     - OSI Model: Network-Rudiments/Subnetting/osi.md
#     - Packet Life: Network-Rudiments/Subnetting/packet-life.md
#     - Numerics: Network-Rudiments/Subnetting/numerics.md
#     - IPv4: Network-Rudiments/Subnetting/IPv4.md
#     - Classy: Network-Rudiments/Subnetting/classy.md
#     - CIDR: Network-Rudiments/Subnetting/cidr.md
#     - Subnet 101: Network-Rudiments/Subnetting/subnetting-101.md
#     - Example: Network-Rudiments/Subnetting/example.md
#     - Lloret Nets: Network-Rudiments/Subnetting/lloret-nets.md
#     - Wild: Network-Rudiments/Subnetting/wild.md
#     - Super Lloret: Network-Rudiments/Subnetting/super-lloret.md
#     - Power: Network-Rudiments/Subnetting/power2.md
#     - Hex: Network-Rudiments/Subnetting/hex.md
#     - IPv6: Network-Rudiments/Subnetting/IPv6.md
#     - Reference Docs: Network-Rudiments/Subnetting/documents.md
#     - Trace: Network-Rudiments/Subnetting/trace.md
#     - Bad: Network-Rudiments/Subnetting/broadcast.md
#   - DNS:
#     - Network-Rudiments/DNS/index.md
#     - Placeholder: Network-Rudiments/DNS/placeholder.md
#   - NAC:
#     - Network-Rudiments/NAC/index.md
#     - Placeholder: Network-Rudiments/NAC/placeholder.md
  
# Vendor Specific 
#  - Vendor Solutions:
#    - Vendors/index.md
#    - Allied Telesis: 
#      - Vendors/Allied-Telesis/index.md
#      - Documents: Vendors/Allied-Telesis/documents.md
#      - Drawings: Vendors/Allied-Telesis/drawings.md
#      - Training: Vendors/Allied-Telesis/training.md
  
# Contact
  - Contact: 
    - Contact: Contact/index.md


# Using the Material theme
theme:
  favicon: assets/favicon/lukeoson-spaceman.png
  custom_dir: docs/overrides
  name: !ENV [THEME_NAME, material]
  icon:
    annotation: material/chevron-right-circle
    repo: fontawesome/brands/github
  name: material
  logo: assets/site-meta/lukeoson-labs-logo.svg
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle: 
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    # MISC
    - header.autohide
    - toc.follow #nav item

    # Navigation 
    - navigation.indexes
    - navigation.tabs
    - navigation.footer
    #- navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    #- navigation.instant.preview
    - navigation.tracking
    - navigation.path
    - navigation.top

    #search
    - search.suggest
    - search.share
    - search.highlight

    #content
    - content.code.copy
    - content.code.select
    - content.code.annotate


extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lukeoson
      name: Lukeoson Labs GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/lukeoson
      name: Lukeoson Twitter
    - icon: fontawesome/brands/twitter
      link: https://bsky.app/profile/lukeoson.bsky.social
      name: Lukeoson Bluesky
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/luke-richardson
      name: Lukeoson LinkedIn
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCXlJsPms5KOc9VLmTjtbYWA
  generator: false 
  homepage: !ENV [HOMEPAGE, https://lukeoson.com]
  # Jinja2
  project: Lukeoson Dabs

# Markdown Extensions
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - md_in_html
  - admonition
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - git-committers:
      repository: lukeoson/lukeoson-mkdocs
      branch: main
  - table-reader:
  - autolinks
  - meta:
      enabled: true
  - macros:
      include_yaml:
        - nav.yml
  - tags:
      tags_file: tags.md
  - glightbox
  - search
  - include-markdown
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: full
      post_excerpt: optional

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js