# Site Settings
site_name: Luke Richardson aka Lukeoson
site_url: https://blah.lukeoson.com/
repo_url: https://github.com/lukeoson/lukeoson-mkdocs
repo_name: lukeoson/lukeoson-mkdocs
copyright: Copyright &copy; 2023 Lukeoson

theme:
  name: material

# Navigation 
nav:
  - Home: index.md
  - Hello: whoami.md

