# Site Settings
site_name: Lukeoson Labs
site_url: https://blah.lukeoson.com/
repo_url: https://github.com/lukeoson/lukeoson-mkdocs
repo_name: lukeoson/lukeoson-mkdocs
copyright: Copyright &copy; 2023 Lukeoson


# Using the Material theme
theme:
  name: material
  icon:
    annotation: material/chevron-right-circle
    repo: fontawesome/brands/github
  name: material
  favicon: assets/logos/favicon.ico
  #logo: assets/logos/lloret-letters-logo.webp 
  features:
    - navigation.tabs
    - navigation.footer
    - header.autohide
    - navigation.sections
    - search.highlight
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - search.suggest
    - search.share


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lukeoson
      name: Lloret Labs GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lukeoson
      name: Lloret Group Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/lloret-control-systems
      name: Lloret Control Systems LinkedIn
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/watch?v=bhhagWXO5V0&list=PLu0ZfvM3i6VmMR85jaX5Enh5D32-p_d9k
  generator: false 
  homepage: https://lloret.co.uk

# Navigation 
nav:
  - Home: index.md
  - Subnetting:
    - Subnetting: Subnetting/index.md
    - Hello: Subnetting/whoami.md
    - Subnet Things: Subnetting/subnetting.md
    - OSI Model: Subnetting/osi.md
    - Packet Life: Subnetting/packet-life.md
    - Numerics: Subnetting/numerics.md
    - IPv4: Subnetting/IPv4.md
    - Classy: Subnetting/classy.md
    - CIDR: Subnetting/cidr.md
    - Subnet 101: Subnetting/subnetting-101.md
    - Example: Subnetting/example.md
    - Lloret Nets: Subnetting/lloret-nets.md
    - Wild: Subnetting/wild.md
    - Super Lloret: Subnetting/super-lloret.md
    - Power: Subnetting/power2.md
    - Hex: Subnetting/hex.md
    - IPv6: Subnetting/IPv6.md
    - Reference Docs: Subnetting/documents.md
    - Trace: Subnetting/trace.md
    - Bad: Subnetting/broadcast.md
  - Allied Telesis:
    - Allied Telesis: Allied-Telesis/index.md
    - Documents: Allied-Telesis/documents.md
    - Drawings: Allied-Telesis/drawings.md
    - Training: Allied-Telesis/training.md
  - Contact: contact.md



markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - md_in_html
  - admonition
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
    

plugins:
  - glightbox
  - search
  - include-markdown
  - table-reader 

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - /javascripts/linkedin.js