authors:
  lukeoson:
    name: Luke Richardson
    description: Network Engineer
    avatar: https://avatars.githubusercontent.com/u/32157545?s=400&u=d53cbf1d24a4dcbf0f6d3217a2c96387b54c55fc&v=4
    url: https://github.com/lukeoson
  lloret-luke:
    name: Luke Richardson
    description: Network Architect @ Lloret Labs
    avatar: https://avatars.githubusercontent.com/u/149865626?v=4
    url: https://github.com/lloret-luke