name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pandoc and LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-latex-extra

      - name: Convert resume to PDF (Apple-style)
        run: |
          mkdir -p docs/assets/brand-profile/resume/
          pandoc docs/Hire-Me/resume-master.md \
            --from markdown \
            --template=docs/templates/eisvogel.latex \
            --pdf-engine=xelatex \
            -o docs/assets/brand-profile/resume/Luke-Richardson-Resume.pdf

      - name: Convert resume to DOCX
        run: |
          pandoc docs/Hire-Me/resume-master.md \
            -o docs/assets/brand-profile/resume/Luke-Richardson-Resume.docx

      - name: Upload Resume Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume-files
          path: docs/assets/brand-profile/resume/

  deploy:
    runs-on: ubuntu-latest
    needs: build-resume

    steps:
      - name: Download Resume Artifacts
        uses: actions/download-artifact@v4
        with:
          name: resume-files
          path: docs/assets/brand-profile/resume/

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Commit resume files to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/assets/brand-profile/resume/
          git commit -m "Update generated resume files" || echo "No changes to commit"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-actions.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-actions.txt
          pip install git+https://${{ secrets.MKDOCS_INSIDERS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git

      - name: Install pngquant
        run: sudo apt-get install -y pngquant

      - name: Build and Deploy MkDocs Site
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          mkdocs gh-deploy --force --clean